- Gemfile.lock
Rack is used by the gds-adapter-gem, so this application is not vulnerable to the recent rack CVE, but upgrade anyhow.
https://groups.google.com/forum/#!msg/rubyonrails-security/gcUbICUmKMc/qiCotVZwXrMJ
> Upgrade rack to 1.6.2

- email_alert_service/models/message_processor.rb
- email_alert_service/validators/document_validator.rb
- spec/models/message_processor_spec.rb
This is in response to errors we've started getting with processing of
redirect documents (which have neither title nor description), and
organisation documents (which have no description).  These document
formats didn't exist in content-store when the service was initially
designed.  Further, until some recent changes in the publishing API,
even when the fields were absent from the document sent to the
publishing API, the message on the message queue had the fields present
with their values set to `nil`, so passed validation here.
"Content" documents should always have a title, so ignoring documents
without them is safe, and has the small benefit of ensuring that there's
no risk of things like "redirect" documents triggering alerts.  Sending
an alert for a document without a title would …
> Handle messages with no title or description

- email_alert_service/models/message.rb
- email_alert_service/models/message_processor.rb
- email_alert_service/validators/document_validator.rb
- spec/integration/major_changes_spec.rb
- spec/models/message_processor_spec.rb
- spec/models/message_spec.rb
Previously, this would error for items without a public_updated_at field
set (ie redirect or gone items).  This is because the check for the
presence of a title happens after the validation.
This has involved some refactoring of the message processor so that it
checks for the title and language before validating the document.
> Don't error on redirect items.

- email_alert_service/models/message_processor.rb
- email_alert_service/validators/document_validator.rb
- spec/models/message_processor_spec.rb
- spec/validators/document_validator_spec.rb
Such messages can be valid (for example, the special_route documents are
valid items).
Rather than raising a validation error for such documents, just ignore
them.
Currently, such documents can never be tagged to topics (since
the topic tags are held in the details hash), but in future it will be
possible for them to be tagged using the links hash, so I've not
implemented this by actively ignoring the documents - instead, I've just
handled a missing details hash the same as one which is present but
empty.
> Handle messages which have no details hash

- email_alert_service/models/email_alert.rb
- email_alert_service/models/email_alert_template.rb
- spec/models/email_alert_spec.rb
Update the email alert model to include a links hash containing a content
ID, if one is present in the payload received from a client app.
This enables support for email alert notifications triggered by either
tags or links. This is an intermediate state as we migrate to using
links/content IDs only.
Includes a second refactoring commit.
Trello: https://trello.com/c/ZD65QUBN/326-email-alerts-based-on-links-hash
> Conditionally include links hash in call to email-alert-api

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
Rather than check for the presence of this key, simply merge the links
of the incoming document in. The email-alert-api will handle matching
and sending alerts to the appropriate subscriber lists.
> Drop check on 'links' => 'parent' in email alert model

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
Currently, MessageProcessor only supports email alerts for documents
that are tagged with either 'topics' or 'policy'. The latter is
incorrect - content items tagged to policies use the tag name
'policies' (plural). This change is intended to fix the behaviour
of policy email alerts in production.
> Change supported tags for email alerts

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
Previously the log string in question made explicit reference to a document's
topic tags. A document may also be tagged to policies. By simply printing the
entire details hash, better (more complete) info is provided about the document's
tagging.
> Update logging info when sending email alert

- email_alert_service/models/email_alert_template.rb
- jenkins.sh
- lib/services.rb
- spec/integration/major_changes_spec.rb
- spec/models/email_alert_spec.rb
- spec/spec_helper.rb
- spec/support/content_item_helper.rb
Currently, the emails sent out to subscribers to policy change alerts have a link
to the policy alert signup page, not to the policy itself.  This change fixes that bug.
https://trello.com/c/JExeIwcb
> Policy Change email alerts to have link to policy

- email_alert_service/models/email_alert.rb
- email_alert_service/models/message_processor.rb
- spec/models/email_alert_spec.rb
- spec/models/message_processor_spec.rb
This checks the incoming document's links hash for the presence of topic
or policy tags. It also cleans up some of the tests related to message
processing and the email alert api payload.
In message_processor_spec.rb in particular, this commit tries to make
the tests easier to follow by mutating the test data in each test case
(rather than setting up multiple, complete test documents at the top of
the spec). It preserves (and builds upon) the variety of scenarios the
processor is supposed to handle.
> Check links hash for tags when determining whether or not to send email

- Gemfile
- Gemfile.lock
This is needed in production, but is not currently listed in the Gemfile.
This will fix problems with deploying this app in integration:
https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/1921/console
> Add Rake to Gemfile

- email_alert_service/models/email_alert.rb
- email_alert_service/models/message_processor.rb
- spec/integration/major_changes_spec.rb
- spec/models/email_alert_spec.rb
We're building email alerting into the service manual.
1) We need documents with a link to `service_manual_topics` to be sent to the email alert api so that they can be matched against possible subscriber lists.
I've also renamed the method from `contains_supported_tag?` to `contains_supported_attribute?` because the method is used for checking both tags and links.
2) The email alert api allows for matching on document type, but the email alert service does not currently send the document type. The only way the document_type matcher can currently be used is by hitting it directly (as travel-advice-publisher does).
This changes the service to always send the document type to the email alert api. The document type should be irrelevant unless a subscriber list is set to match against it, so …
> Allow documents with service manual topics to trigger emails

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
We want users to be able to subscribe to changes to the service manual standard points. Points are just guides where the service standard is the parent. We don't want to send all documents with parents to the email alert api. Instead we send all the guides and let the email alert api work it out.
> Send all service manual guides to email alert api

- Jenkinsfile
These build parameters are only required by projects which are used to test changes to the content schema.
I should have spotted this in the previous PR, sorry!
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration
> Delete unnecessary build parameters

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
To fix https://errbit.publishing.service.gov.uk/apps/545387cd0da115367c00f0c6/problems/584fd0a36578630e38c70700
See the commit notes for the story, but the tl;dr is that `Hash#fetch` doesn't protect us against keys with `nil` values.
/cc @tijmenb, @alexmuller, @jennyd
> Robustly detect missing attributes

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
Added content_id, publishing app and public_updated_at fields so that
EmailAlertApi can use them in the logs.
This will allow greater visibility of how the matching works and
mean we can compare against what is matched in GovUkDelivery in preparation
for the migration.
https://trello.com/c/b9ZonGXn/121-logging
> Add logging parameters for EmailAlertApi

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
Pass the new email_document_supertype and
government_document_supertype fields thorugh.
These are required for the govuk delivery migration.
https://trello.com/c/5yVMib2f/124-2-add-support-for-whitehall-topics-in-new-email-stack
> Pass supertype fields to email alert API

- email_alert_service/models/email_alert_template.rb
- spec/models/email_alert_template_spec.rb
We would like to include the change note in the email, if we can - it's
helpful for users to have the context of what's changed so they know if it's
relevant to them.
There are a variety of places in content items where change notes can be,
depending on the document type. We were previously only looking in one of
these places, which meant that most emails constructed by email-alert-service
didn't include a change note.
The publishing API tries to store change notes in a consistent format, and has
recently been fixed to ensure that that is done more often [1]. That means
that we should have a "change_history" array in the details hash in the
messages from the queue, in reverse chronological order. This commit switches
to using the first (most recent) change note from there in the email …
> Use first note from change_history in email body

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
We need to trigger emails via email-alert-api for a wider range of content in order to support the Whitehall subscriptions. This change expands the list of attributes to look for in `links` and `tags`, as well as looking for the two relevant document supertype fields, and passes on more content to email-alert-api based on those checks.
We're moving towards almost all of our email alerts relying on the message queue (and therefore email-alert-service) but travel advice publisher and specialist publisher still make direct calls to email-alert-api to send their emails. We want to be particularly careful to not send those emails twice, especially when expanding the scope of the filtering, so this PR adds an extra check to explicitly exclude content from those two publishing apps.
> Support criteria for Whitehall subscriptions

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
`DocumentValidator` checks that 3 required fields are present as keys in the
document, but doesn't check their values. `MessageProcessor` checks the values
of two of those three plus `locale`, but wasn't checking that `base_path` had a
useful value.
When we expanded the filtering to include more content to support the
Whitehall subscriptions, we started trying to process some messages for
Whitehall contacts, which are non-addressable content items. They have a `nil`
`base_path` (in the representation that comes through on the queue, anyway) so
were passing the earlier checks but erroring when trying to construct the
message body (in `EmailAlertTemplate#make_url_from_document_base_path`).
This commit expands the earlier checks to ensure that if a message has a `nil`
`base_path` it is …
> Add check for base_path value being present

- Gemfile
- Gemfile.lock
- email_alert_service/models/email_alert.rb
- email_alert_service/models/taxon_tree.rb
This brings the code to generate the taxon tree into this app. The taxonomy gem was part of an effort to avoid duplication between applications dealing with the taxonomy. Unfortunately we ran out of time last quarter, which left us with an API that was still in flux (https://github.com/alphagov/govuk_taxonomy_helpers/pull/11).
To avoid confusion, I think it's best to inline the code in the places where we use the taxonomy helpers. We're going to be doing work around the taxonomy in the next couple of months and I think it will be easier to extract code than trying to nail the API right now.
Trello: https://trello.com/c/FVfbiKxn
> Inline the code to generate the taxon tree

- Gemfile.lock
Downstream tests for email-alert-service are failing due to `govuk_schemas` not
being up to date, so this updates the gem to 2.1.1.
> Update govuk_schemas version to 2.1.1

- email_alert_service/models/taxon_tree.rb
Links aren't a required property of frontend links [1] this code
previously assumed that links would exist and only checked for
"parent_taxons" within it. This can result in a undefined method on nil
error.
This is only a problem in testing as in production a links has is always
existent. I hesitate to add that as a required field as I don't think it
always makes sense to exist.
[1]:
https://github.com/alphagov/govuk-content-schemas/blob/master/formats/frontend_links_definition.json
> Don't assume there are links

- bin/email_alert_service
- email_alert_service/environment.rb
`govuk_app_config` is not available from within the context of the `email_alert_service` script, so we require it from `environment.rb` after rubygems has been loaded instead.
> Fix Sentry integration

- config/rabbitmq.yml
- email_alert_service/config.rb
The rabbitmq hostnames are hardcoded in our deployment scripts, and this means this application won't be able to work properly with rabbitmq when running in Amazon (where we use different hostnames).
Allow the config file to be read in as ERB so we can set a conditional based upon environment variables.
https://trello.com/c/fenlgsMp/745-make-icinga-in-aws-green
> Allow rabbitmq config to be passed in as env var

- config/redis.yml
- email_alert_service/config.rb
Ensure the redis configuration is read from env var so that all configuration is read in from environment variables set in Puppet.
https://trello.com/c/fenlgsMp/745-make-icinga-in-aws-green
> Ensure redis config reads from env var

- Gemfile
- Gemfile.lock
- email_alert_service/models/email_alert_template.rb
- spec/models/email_alert_template_spec.rb
This commit changes the output of the email-alert-api to GovDelivery to convert all times to local time in London from the default UTC that comes from publishing-api to match user expectations.
Trello: https://trello.com/c/SzDmoENZ/260-publication-date-for-whitehall-announcements-reported-in-email-digests-may-be-in-utc-not-bst
> Convert UTC to local time

- email_alert_service/environment.rb
- email_alert_service/models/change_history.rb
- email_alert_service/models/email_alert.rb
- email_alert_service/models/email_alert_template.rb
- spec/models/change_history_spec.rb
- spec/models/email_alert_spec.rb
This PR adds the extra fields `change_note`, `base_path`, `title` and `description` to the payload sent to email-alert-api. This information is also sent within `subject` and `body` but we are moving towards making the generation of these the responsibility of email-alert-api so we need the raw data fields.
In adding the `ChangeHistory` class to encapsulate the logic for that that is used in both `EmailAlert` and `EmailAlertTemplate` now I've realised that the requiring of things in this app is all over the place and seems to be working mostly by luck.
I'll try and address that in another PR. 
[Trello](https://trello.com/c/10k5XPez/264-add-title-and-changenote-to-email-alert-service)
> Add fields to email alert api payload

- bin/delete_queue
- bin/email_alert_service
- email_alert_service/environment.rb
- email_alert_service/models/email_alert.rb
- email_alert_service/models/lock_handler.rb
- email_alert_service/models/message_processor.rb
- spec/connections/connection_spec.rb
- spec/integration/random_input_spec.rb
- spec/listeners/listener_spec.rb
- spec/models/message_processor_spec.rb
- spec/queues/major_change_queue_spec.rb
- spec/support/listener_test_helpers.rb
Prior to this commit models were required in a couple of places that as luck would have it made them available where the were needed.
When trying to add another model ([in another PR](https://github.com/alphagov/email-alert-service/pull/86)) it wasn't clear why it was undefined in its specs but other models seemingly got required by magic.
This commit loads all models in the environment which is included in both spec_helper and the application entry point - bin/email_alert_service.
Should we do this for the other objects? `connections`, `listeners` and `queues`?
> Require all models in environment

- email_alert_service/models/email_alert.rb
Email-alert-api is getting authentication and authorisation. This commit adds a bearer token for it when creating the client.
[Trello](https://trello.com/c/75sVuXhA/455-require-all-apps-to-authenticate-with-email-alert-api)
> Add bearer token for email-alert-api

- Gemfile
- Gemfile.lock
Reverts alphagov/email-alert-service#100
This broke the ability for email-alert-service to connect to the Rabbit MQ.
```
W, [2017-12-29T10:19:37.347426 #28223]  WARN -- #<Bunny::Session:0x7f78baaadd60 @localhost:5672, vhost=, addresses=[localhost:5672]>: Connection options contain both a host and an array of hosts (addresses), please pick one.
W, [2017-12-29T10:19:37.348853 #28223]  WARN -- #<Bunny::Session:0x7f78baaadd60 email_alert_service@localhost:5672, vhost=/, addresses=[localhost:5672]>: Could not establish TCP connection to localhost:5672: Connection refused - connect(2) for 127.0.0.1:5672
```
> Revert "Bump bunny from 1.5.1 to 2.8.0"

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
Trello: https://trello.com/c/Uo9V91U4/481-stop-sending-email-alerts-for-content-that-is-coming-soon
These shouldn't be sent out as emails as it means users just receive a
message that says "coming soon" which isn't useful to the user.
> Blacklist coming_soon document_type from emails

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
This PR makes sure that travel advice documents and medical safety alerts will be sent out as high priority emails.
Those documents do not currently go through the email alert service, but this will be ready for when they do.
Depends on https://github.com/alphagov/email-alert-api/pull/382
[Trello Card](https://trello.com/c/mHXNdskh/550-setup-delivery-priorities)
> Assign high priorities to travel advice and medical safety documents

- email_alert_service/models/message_processor.rb
This app doesn't manage any content where it would make sense to subscribe to email updates.
[Trello Card](https://trello.com/c/X27iZdG5/568-blacklist-content-changes-from-collections-publisher-in-email-alert-service)
> Blacklist collections-publisher

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
Email-alert-api now checks for duplicate content changes and returns a 409 if they are received.
This PR rescues and logs the GdsApi::HTTPConflict that will be raised by the adapter.
> Don't retry 409s from email-alert-api

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
We've found the descriptions to be excessively long so we don't want them to be included in emails.
[Trello Card](https://trello.com/c/2MgWX34y/642-change-what-we-put-in-travel-advice-updates)
> Don't send descriptions for travel advice emails

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
These aren't the kind of document types we would expect users to need to subscribe to.
> Blacklist special route document types

- email_alert_service/models/message_processor.rb
- spec/integration/major_changes_spec.rb
- spec/models/message_processor_spec.rb
This checks the documents that are plucked from the queue to see if they
have a change note, if they do not they are not sent to email-alert-api.
> Don't send emails for documents without a change note

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
This commit blocks HMCTS content items from triggering emails. This will be used temporarily whilst HMCTS forms are migrated to GOV.UK to stop them generating emails and will be removed once the migration is complete.
Trello: https://trello.com/c/n2DVjtf7/573-stop-emails-being-sent-for-hmcts-forms-migration
> Don’t send emails for HMCTS content items

- email_alert_service/models/message_processor.rb
- spec/models/message_processor_spec.rb
This reverts commit 5dff395d80d96ac54d08ea62cc2ae8d0c0cf8b89.
Blocking emails for HMCTS content was temporary, while we bulk-published some imported forms. All the content has been published, so the block should be removed.
https://trello.com/c/pEencybh/89-hmcts-step-3b-spike-suppression-of-emails-being-sent-on-publish
Marked as "do not merge" because we shouldn't deploy this until the 21st of March.
cc @rubenarakelyan
> Revert "Don’t send emails for HMCTS content items"

- email_alert_service/models/change_history.rb
- spec/models/change_history_spec.rb
- spec/models/email_alert_spec.rb
- spec/models/message_processor_spec.rb
This ignores the order of the change notes in the array and instead sorts by the date so it is always the latest one.
[Trello Card](https://trello.com/c/APBoUkYx/732-investigate-change-history-handling-in-email-alert-service)
> Always pick the latest change note regardless of order

- config/rabbitmq.yml
During deployment of the updates to the email-alert-service (https://github.com/alphagov/email-alert-service/pull/178) email-alert-api (https://github.com/alphagov/email-alert-api/pull/655) and the gds-api-adapters (https://github.com/alphagov/gds-api-adapters/pull/846),
the unpublishing events were temporarily disable to enable testing of these modules
individually
This PR enables the unpublishing events
trello: https://trello.com/c/fPAplaaV/67-send-notifications-when-unpublishing-taxons
> Enable unpublish events to be forwarded to email-api-service

- config/rabbitmq.yml
The routing key for unpublishing messages was incorrect. This PR fixes that.
> Fix a mistake in the routing key

- email_alert_service/listeners/listener.rb
Currently when an exception occurs, we try and access a variable called `e` which doesn't exist. This means the whole program crashes but upstart doesn't restart it since it hasn't exited, it's just blocking.
I think this is the reason why we've seen email-alert-service sometimes stop processing the queue, and it seems related to when RabbitMQ is unreachable in some way. Hopefully this fix should mean that we can see what the error is next time.
It looks like this bug was introduced in https://github.com/alphagov/email-alert-service/commit/658816212c418541187598713dbcca921f3cb3ef.
> Fix exception handling

- spec/listeners/listener_spec.rb
If an error occurs while processing a message, the app should report the error and exit cleanly. We had an incident recently where this process wasn't working correctly and ended up leaving the service running but not processing anything.
[Trello Card](https://trello.com/c/Nq48ujFz/871-add-a-test-to-email-alert-service-for-when-the-connection-to-rabbitmq-is-lost)
> Add a test to check process exits cleanly

- Dockerfile
- Jenkinsfile
- lib/tasks/message_queues.rake
Trello: https://trello.com/c/odtNdsay/574-e2e-tests-failing-since-monday-morning
This adds a few changes that aim to resolve problems running the end-to-end tests.
This depends on https://github.com/alphagov/publishing-e2e-tests/pull/326 and the end-to-end test result here is based on that.
This firstly makes this repo run the end-to-end tests as part of it's build so that it is harder for this app to break the build. This is a slightly annoying situation as the end-to-end tests aren't actually being tested but apps (Content Tagger) do break without them.
This then adds a rake task to create the RabbitMQ queues that are used by this app. I'm not sure whether these were used / worked before. 
Finally this updates the dockerfile to reflect the deprecation of the bin/email_alert_service …
> Fix working with end-to-end tests

- README.md
The Email Alert Service now uses the `govuk_message_queue_consumer` gem,
and the way of starting the service has changed.
> Update Readme to remove reliance on RabbitMQ

- email_alert_service/models/email_alert.rb
- spec/models/email_alert_spec.rb
This method was recently renamed in the [latest version of GDS API Adapters](https://github.com/alphagov/gds-api-adapters/pull/948).
[Trello Card](https://trello.com/c/5rtAmAjc/54-finish-the-messages-endpoint-work-in-email-alert-api)
> Use create_content_change instead of send_alert

- email_alert_service/models/major_change_message_processor.rb
- spec/models/major_change_message_processor_spec.rb
https://trello.com/c/KNWv9Dgx/258-not-ready-to-start-deprecate-and-remove-legacy-email-signup-pages
Previously we added a rule that allowed for alerts to be triggered when a
service_manual_guide was published, in order to accommodate the
subscriptions to the service standard, which is a singleton index page for
several guides [1]. Allowing based on document type is not ideal because
it's unclear what subscriptions this might trigger updates for. This
replaces the original approach by fully articulating the conditions for
which an alert should trigger.
[1]:
https://github.com/alphagov/email-alert-service/commit/1db3c0e34896eae8b7adfa938e11c509fd35e591
> Rescope email alerts for the service standard

- Gemfile
- Gemfile.lock
Use the Gemfile.lock to manage the versions instead which should make it easier to upgrade as it allows bundler a wider set of versions to resolve the dependencies.
(Part of the work to upgrade to Ruby 2.7.1 but no other changes were necessary)
> Remove constraints from dependencies in Gemfile

- email_alert_service/config.rb
https://trello.com/c/F8uizllI/537-fix-kibana-not-ingesting-email-alert-service-logs
Please see the commits for more details.
> Fix log ingestion (format logs as JSON)

- email_alert_service/config.rb
https://trello.com/c/F8uizllI/537-fix-kibana-not-ingesting-email-alert-service-logs
This is no longer necessary since non-JSON logs are now accepted [1].
[1]: https://github.com/alphagov/govuk-puppet/pull/10759
> Remove custom JSON log formatting

- config/initializers/redis.rb
- config/redis.yml
- email_alert_service/config.rb
Trello: https://trello.com/c/dXud4WIt/206-inconsistent-redisurl-config
This is one of the few GOV.UK projects that uses this old approach to
configuring Redis - whereas most of the other ones use the approach
supported natively by the Redis gem [1] of using REDIS_URL. Removing
this will allow us to remove the need for REDIS_HOST and REDIS_PORT env
vars in our architecture and also allows this code to be simplified.
[1]: https://github.com/redis/redis-rb
> Remove need for REDIS_HOST and REDIS_PORT env vars

- README.md
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This follows the pattern established in [1].
[1]: https://github.com/alphagov/content-publisher/pull/2257
> Revise tech docs in README to favour GOV.UK Docker

- lib/tasks/message_queues.rake
As part of the work to enable continuous deployment of all GOV.UK
apps we need to add a check for connectivity to Redis. Since Email
Alert Service is not a web app, this check had to be added to the rake
task that is called at startup time. This commit adds a call to the
Redis service that will throw an error if it does not exist.
https://trello.com/c/AGNZWDFJ/2693-enable-continuous-deployment-for-email-alert-service-3
> Add Redis check to rake task

- email_alert_service/models/unpublishing_alert.rb
- spec/models/unpublishing_alert_spec.rb
[Trello](https://trello.com/c/mQNmwCo2/1140-send-users-an-email-when-a-single-page-is-unpublished)
> Fix email-api uses slugs not uuids called id

- email_alert_service/models/unpublishing_alert.rb
- spec/models/unpublishing_alert_spec.rb
[Trello](https://trello.com/c/mQNmwCo2/1140-send-users-an-email-when-a-single-page-is-unpublished)
The `title` key isn't in the message payload, so log `base_path` instead 
as that's likely to be most useful if debugging in the future.
> Log base path for unpublishing events

- email_alert_service/presenters/unpublishing_message_presenter.rb
- spec/models/unpublishing_alert_spec.rb
- spec/presenters/unpublishing_message_presenter_spec.rb
Because we were going via `Time.now` instead of `Time.iso8601`, we
were losing information and ending up with midnight on the 1st of
January (this year).
I've updated the tests to go more directly from a `Time` object to the
formatted time, which catches this, and then fixed the code.
---
[Trello card](https://trello.com/c/mQNmwCo2/1140-send-users-an-email-when-a-single-page-is-unpublished)
> Correctly parse public_updated_at timestamps

- lib/tasks/message_queues.rake
This is something we spotted when doing the update email list work
> Add missing error and redis config to unpublishing rake task

- spec/models/email_alert_spec.rb
- spec/models/unpublishing_alert_spec.rb
When implementing the unpublishing alert feature, we merged code with
a bug which was passing all the tests.  The bug was that we were
calling a method in gds-api-adapters with incorrect arguments.
This bug passed the tests because the tests do not actually use
gds-api-adapters, they mock those methods and check that the mocked
methods are called appropriately.
This is a problem for two reasons:
1. It let us write code which looked correct and even passed tests,
but which could only have been verified as correct by consulting a
different repository.
2. An update to gds-api-adapters could change the method signature and
our tests would continue to pass on the dependabot branch, even though
merging it would break the service.
The point of testing is to catch bugs.  If a test actively …
> Change the alert specs to use webmock

- Gemfile.lock
- Procfile
- config/rabbitmq.yml
- email_alert_service/models/email_unpublishing_processor.rb
- email_alert_service/models/major_change_message_processor.rb
- email_alert_service/models/message_processor.rb
- email_alert_service/models/subscriber_list_details_update_processor.rb
- email_alert_service/models/unpublishing_alert.rb
- email_alert_service/models/update_subscriber_list.rb
- lib/email_alert_api_helpers.rb
- lib/tasks/message_queues.rake
- spec/lib/email_alert_api_helpers_spec.rb
- spec/models/subscriber_list_details_update_processor_spec.rb
- spec/models/update_subscriber_list_spec.rb
[Trello](https://trello.com/c/IkYegsOt/1225-update-subscriberlist-titles-on-major-minor-publishing-change)
Depends on
=========
https://github.com/alphagov/email-alert-api/pull/1704
(and it's release)
What
====
The GOV.UK Accounts team added a feature where logged in users could
subscribe to email notifications for individual pages.
SubscriberLists store the titles of those pages so that we can:
- Render a list of subscriptions in the user's manage dashboard
- Include the title of the subscriber list in emails alerting the user
that the page has been unpublished. (Especially as there's no-longer a
content item we can query for title at that point).
We record these titles when the SubscriberList is first made, however
there has not been a mechanism to update it. This is a problem as …
> Update subscriber list titles on major / minor publication events

- email_alert_service/models/unpublishing_alert.rb
- email_alert_service/presenters/unpublishing_message_presenter.rb
- spec/models/unpublishing_alert_spec.rb
- spec/presenters/unpublishing_message_presenter_spec.rb
We have added descriptions to single page subscription lists which are
the page summary from the content item. Add these descriptions to the
emails about a single page being unpublished so the emails have more
context for users.
Do not merge until the rake task added in [[1]] has been run against
production. This is to ensure all single page subscriber lists have a
non-null description.
[Trello](https://trello.com/c/dm5ZxFVB/1226-pass-through-page-descriptions-to-subscriberlists-on-major-minor-publishing-change)
[1]: https://github.com/alphagov/email-alert-api/pull/1708
> Add page summary to unpublished emails

- docs/special-cases-for-single-page-notifications.md
[Rendered](https://github.com/alphagov/email-alert-service/blob/msw/single-page-docs/docs/special-cases-for-single-page-notifications.md)
Currently it's just unpublishing, but we would also like to tackle
list metadata at some point.
> Add documentation on the special cases for single-page notifications

- Gemfile.lock
- email_alert_service/models/lock_handler.rb
Allows updates to Redis 5+
In redis-rb 5+, .multi and .pipeline blocks must have arity 1, and use that method for the pipelined/transaction methods called in the block.
https://trello.com/c/DM2bDFAB/1508-upgrade-redis-421-to-502-in-email-alert-service
> Update redis gem, update to  pipeline block parameter as required.

- .dockerignore
- Dockerfile
- Gemfile
- Gemfile.lock
- email_alert_service/environment.rb
- Use bootsnap to reduce startup resource usage spike.
- Parameterise Ruby version.
- Make better use of WORKDIR.
- Use env vars from the base image where appropriate, instead of hardcoding paths.
- Remove unnecessary use of `bundle exec`.
- Update .dockerignore.
Tested: app boots successfully with `docker run`.
> Dockerfile cleanup + enable bootsnap.

- Dockerfile
- bin/email-alert-service
- email_alert_service/config.rb
- email_alert_service/environment.rb
- lib/tasks/message_queues.rake
On Kubernetes it's simpler and more efficient to run the four consumer processes in the same Pod than to run a separate Deployment for each.                                 
The simplest way to do this is to fork and have the parent process exit if any of the child processes exit.                                
The main motivation for this change is to avoid having to add weirdness to the Prometheus scrape config and run [prometheus_exporter] on multiple ports in the same Pod, which is what we'd have to do if we were to keep the application as-is.
Avoiding the (mis)use of Rake to start the application simplifies the startup process and makes it easier to understand the control flow during initialisation. For example it turns out that Bootsnap was being initialised much later than it's …
> Add a single entrypoint that runs all consumers.

- Gemfile.lock
These are brough in by sentry-rails, not really needed for this app but can't be got rid of without a change to govuk_app_config.
This is a manual fix for the failing dependabot PR: https://github.com/alphagov/email-alert-service/pull/627
> Bump railties-related gems to 7.0.43

- .dockerignore
- Jenkinsfile
- Procfile
- lib/tasks/message_queues.rake
- Remove Rake tasks which are disused after moving to Kubernetes.
- Remove disused Procfile and Jenkinsfile.
> Replatforming post-launch cleanup.
